version: '3.2'

services:
  ros-foxy-talker:
    build:
      context: ./ros-docker-context/
    command: ["ros2", "run", "demo_nodes_py", "talker"]
    networks:
      - ros-test-net
    ports:
      - "${HOST_IP}:7412:7412/udp"
      - "${HOST_IP}:7413:7413/udp"
    environment:
      RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
      CYCLONEDDS_URI: "<CycloneDDS><Domain id='any'><General><ExternalNetworkAddress>${HOST_IP}</ExternalNetworkAddress><AllowMulticast>false</AllowMulticast></General><Discovery><ParticipantIndex>1</ParticipantIndex><Peers><Peer address='${HOST_IP}'/></Peers></Discovery><Tracing><Verbosity>config</Verbosity><Out>stderr</Out></Tracing></Domain></CycloneDDS>"

networks:
  ros-test-net:
    driver: bridge